### ISSUE TITLE
the tilde doesn't work in path

### ISSUE THREAD

**Issue by stephane-archer** [caian-org/ansible-stow#2]
The following doesn't work:
```
 stow:
    state: present
    package: zsh
    dir: ~/dots
```
but this does
```
 stow:
    state: present
    package: zsh
    dir: /home/myname/dots
```

Thank you for making this great ansible module
